'use strict';
const { v4: uuid } = require("uuid");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
      await queryInterface.bulkInsert("Products", [
        {
          id: uuid(),
          kodebarang: "02.04.041.00.011",
          namabarang: "BLADE W2.0-01-01-03G-03-05",
          image: "https://i.ibb.co/ZNxcp3g/Untitled-design-1.png",
          image2: "https://i.ibb.co/JkSSmRZ/Untitled-design-2.png",
          image3: "",
          typebarang: "cluster_0",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 25000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.13.095.00.069",
          namabarang: "13 TOOTH SPROKET II",
          image: "https://i.ibb.co/4ttPZ1v/Untitled-design.png",
          image2: "https://i.ibb.co/fdNGjJb/Untitled-design-3.png",
          image3: "",
          typebarang: "cluster_0",
          deskripsibarang: "Maxxi Original Sparepart",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 140000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.05.006.02.001",
          namabarang: "CHAIN WHEEL WELD",
          image: "https://i.ibb.co/GcdK9j6/Untitled-design-3.png",
          image2: "https://i.ibb.co/418rhNd/Untitled-design-4.png",
          image3: "",
          typebarang: "cluster_0",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 425000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.19.004.00.083",
          namabarang: "OSCILLATING BEARING",
          image: "https://i.ibb.co/dthsWWK/Untitled-design.png",
          image2: "https://i.ibb.co/VCwXL0N/Untitled-design-5.png",
          image3: "",
          typebarang: "cluster_0",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 240000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "02.20.096.00.054",
          namabarang: "OIL SEAL",
          image: "https://i.ibb.co/SQHGRQx/Untitled-design-1.png",
          image2: "https://i.ibb.co/0DZpcKJ/W1-8-33-06-04-00.png",
          image3: "https://i.ibb.co/jMMjSqy/Untitled-design-6.png",
          typebarang: "cluster_0",
          deskripsibarang: "MAXXI Original Spare Parts",
          stockbarang: 1,
          satuanbarang: "pcs",
          price: 350000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "1",
          namabarang: "Sofa L Besar",
          image: "https://ibb.co/bW0W8Vb",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Bonus Bantal 10 pcs, Kayu Akasia Bayur",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   id: uuid(),
        //   kodebarang: "2",
        //   namabarang: "Sofa L Minimalis",
        //   image: "https://ibb.co/C5shR3L",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 4 pcs, Kayu Akasia Bayur, Free Ongkir Bandar Lampung,", 
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2100000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "3",
        //   namabarang: "Sofa L",
        //   image: "https://ibb.co/xgHqbm3",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 3 pcs, Kayu Akasia Bayur, Free Ongkir Bandar Lampung,",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2000000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "4",
        //   namabarang: "Sofa L",
        //   image: "https://ibb.co/b3pmfF6",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, Kayu Akasia Bayur",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2000000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "5",
        //   namabarang: "Sofa L Besar",
        //   image: "https://ibb.co/qgwgkP8",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 10pcs, Kayu Akasia Bayur",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "6",
        //   namabarang: "Sofa Retro L",
        //   image: "https://ibb.co/YXjPmBX",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, Bahan Kain Kagawa, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 1800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "7",
        //   namabarang: "Sofa Retro L putus",
        //   image: "https://ibb.co/hWqg888",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, bahan kain spon, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 1800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "8",
        //   namabarang: "Sofa Retro L putus ",
        //   image: "https://ibb.co/mHX40Ry",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5pcs, Bahan Kain Mulan/Galaxi, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 1800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "9",
        //   namabarang: "Sofa Retro L putus",
        //   image: "",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, Bahan Kain Kagawa, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2400000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "10",
        //   namabarang: "Sofa L ",
        //   image: "https://ibb.co/VBt8rtH",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, Bahan Kain Foxi, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2500000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "11",
        //   namabarang: "Sofa Retro",
        //   image: "https://ibb.co/JKfMnc4",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus bantal 3 pcs, Kain Kagawa, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 1800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "12",
        //   namabarang: "Sofa Retro",
        //   image: "https://ibb.co/yVdw1jh",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 4 pcs, Kain Kagawa, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2600000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "13",
        //   namabarang: "Sofa Retro ",
        //   image: "https://ibb.co/ZBnb0BX",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 4 pcs, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2000000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "14",
        //   namabarang: "Sofa Retro",
        //   image: "https://ibb.co/196S4ck",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal Besar Dan Kecil, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2500000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "15",
        //   namabarang: "Sofa Retro L Putus",
        //   image: "https://ibb.co/C1DzLr3",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 6 pcs, Bahan Kain Sahrini, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 4700000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "16",
        //   namabarang: "Sofa Retro L",
        //   image: "https://ibb.co/zGrqSjf",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 3 pcs, Bahan Kain Medili, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "17",
        //   namabarang: "Sofa Retro L",
        //   image: "",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 3 pcs, Bahan Kain Foxi,Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2000000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "18",
        //   namabarang: "Sofa Retro",
        //   image: "https://ibb.co/JxqLLDX",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 4 pcs, Bahan Kain Bludru Poxi, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2800000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   id: uuid(),
        //   kodebarang: "19",
        //   namabarang: "Sofa L",
        //   image: "",
        //   image2: "",
        //   image3: "",
        //   typebarang: "Sofa",
        //   deskripsibarang: "Bonus Bantal 5 pcs, Kayu Akasia Bayur, Free Ongkir Bandar Lampung",
        //   stockbarang: 10,
        //   satuanbarang: "pcs",
        //   price: 2000000,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
      ]);
    },
  
    async down(queryInterface, Sequelize) {
      await queryInterface.bulkDelete("Products", null, {});
    },
  };
  
